### ISSUE TITLE
dyntime.js: dateformat.day() returns "13rd" instead of "13th"

### ISSUE THREAD

**Issue by DJDavid98** [ponydevs/MLPVC-RR#3]
Problematic check (missing `date == 13`): [/www/js/dyntime.js#L33](https://github.com/ponydevs/MLPVC-RR/blob/85165957f9b103e3f3b0a45ce175059c135552b0/www/js/dyntime.js#L33)

Posting it as an issue so I remember to fix it later.

**Comment by tjhorner** [comment]
Why did you use `postfix` instead of `suffix`?

**Comment by jamesmanning** [comment]
Haven't really looked at this, but when it comes to formatting things like
dates, I love using moment.js

http://momentjs.com/docs/#/displaying/format/

**Comment by tjhorner** [comment]
@jamesmanning agreed. moment.js is great.

**Comment by DJDavid98** [comment]
@tjhorner Because my english is bad and I didn't know the correct term.

As for moment.js, I'll look into implementing it later.

**Comment by tjhorner** [comment]
@DJDavid98 lel, okay.
