### ISSUE TITLE
Provide a list of colors as csv file or similar

### ISSUE THREAD

**Issue by abrock** [ponydevs/MLPVC-RR#32]
I'd like to run statistics on colors, could you provide a (script for creating a) simple csv file or similar?

I need something like this:

"Nightmare Moon" "Fill" "#000000"

**Comment by DJDavid98** [comment]
So the coat fill color for each character?

**Comment by abrock** [comment]
not only the coat fill, also the mane fill and outlines and every other color, I want to test hypotheses like "the outline colors can be explained by a linear function of the fill colors" etc.

**Comment by DJDavid98** [comment]
A lot of characters have multiple mane fills, in that case, what colours? Also, you could just install PostgreSQL, import the dump, and write an SQL query to get the data yourself. If you desperately need a script from me, you have to specify exactly what you need and how.

**Comment by abrock** [comment]
I'm not sure I got the join right since, does this statement correctly matches ponies and their colors?

```sql
select
appearances.label,
colorgroups.label,
colors.label,
colors.hex

from appearances, colorgroups, colors
where
    appearances.id = colorgroups.ponyid
and colorgroups.groupid = colors.groupid
```

**Comment by DJDavid98** [comment]
Running the query, these are the first set of results I get which seem to be accurate.

label | label | label | hex
------ | ------ | ------ | ----
Twilight Sparkle | Coat | Outline | #A46BBD
Twilight Sparkle | Coat | Fill | #CC9CDF
Twilight Sparkle | Coat | Shadow Outline | #9156A9
Twilight Sparkle | Coat | Shadow Fill | #BF89D1
Twilight Sparkle | Mane & Tail | Outline and Inner Lines | #132248
Twilight Sparkle | Mane & Tail | Fill | #243870
Twilight Sparkle | Mane & Tail | Stripe 1 | #652D87
Twilight Sparkle | Mane & Tail | Stripe 2 | #EA428B
Twilight Sparkle | Iris | Gradient Top | #1E093C
Twilight Sparkle | Iris | Gradient Bottom | #662F89
Twilight Sparkle | Iris | Highlight Top | #8D5DA4
Twilight Sparkle | Iris | Highlight Bottom | #CCB2D3
Twilight Sparkle | Cutie Mark | Large Star | #EA428B
Twilight Sparkle | Cutie Mark | Small Stars | #FFFFFF
Twilight Sparkle | Magic | Aura | #EA428B
... | ... | ... | ...

You may want to rename some columns using `as`:
```
select
appearances.label as appearance,
colorgroups.label as colorgroup,
colors.label as color,
colors.hex
```
so if you parse it with an application you can get each column's value.

**Comment by abrock** [comment]
Thank you for your help, I think I can get it done now :-)
